#!/usr/bin/env bash
set -eo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

source "$PROJECT_DIR/scripts/bootstrap"
source "$PROJECT_DIR/scripts/modules/workdir"
source "$PROJECT_DIR/scripts/modules/manifests"
source "$PROJECT_DIR/scripts/modules/userscripts"
source "$PROJECT_DIR/scripts/modules/docker"

check_deps
require_var DEVICE_LIST
require_var BRANCH_NAME
: "${ROOT_METHOD:=none}"

export_config
export ROOT_METHOD

workdir_init "base"
local_manifests_clear
userscripts_write_before_sh

docker_run_lineage "false"
